version: '3.9'

services:
  openwrt:
    image: honyua/openwrt:latest
    container_name: openwrt
    restart: always
    command: /sbin/init
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/root/docker.sock
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.35  # 替换为你的局域网IP段内地址
  cfnat:
    container_name: mycfnat
    image: cmliu/cfnat:latest
    environment:
      - colo=HKG  # 筛选数据中心例如 HKG,SJC,LAX.电信/联通 推荐 SJC,LAX.移动/广电 推荐 HKG"
      - delay=150  # 有效延迟（毫秒），超过此延迟将断开连接
      - ips=4  # 指定生成IPv4还是IPv6地址
      - port=443  # 转发的目标端口
      - tls=true  # 是否为 TLS 端口
      - random=true  # 是否随机生成IP，如果为false，则从CIDR中拆分出所有IP
      - ipnum=5  # 提取的有效IP数量
      - num=10  # 目标负载 IP 数量
      - task=100  # 并发请求最大协程数
      - code=200  # HTTP/HTTPS 响应状态码
      - domain=cloudflaremirrors.com/debian # 响应状态码检查的域名地址
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.36  # 替换为你的局域网IP段内地址
    ports:
      - "1234:1234"  # 将主机的 1234 端口映射到容器的 1234 端口
    restart: always

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0  # 替换为你的宿主机物理网卡名
    ipam:
      config:
        - subnet: 192.168.1.0/24   # 替换为你局域网的网段
          gateway: 192.168.1.1     # 替换为你局域网的网关
